### ISSUE TITLE
Failing tests on Windows (all) and OSX (Python 2.7 only)

### ISSUE THREAD

**Issue by jakevdp** [conda-forge/pyamg-feedstock#1]
The test suite for pyamg 3.0.2 fails on windows (see https://github.com/pyamg/pyamg/issues/168) and on OSX with Python 2.7 (see https://github.com/pyamg/pyamg/issues/165).

Currently these are skipped in the test phase of the recipe: https://github.com/conda-forge/pyamg-feedstock/blob/master/recipe/run_test.py

When future pyamg versions are released, these skipped tests should be revisited.

**Comment by pelson** [comment]
Just to clarify, it doesn't really scale to run the _full_ test suite of each package when building. Instead we want to be able to run only the tests which assert that a package has been installed correctly. It is a tricky balance to find and often "good enough" is highly subjective.

**Comment by jakevdp** [comment]
Oh – didn't know that. Should I modify `pyamg` and `megaman` to not run the test suite then?

**Comment by ocefpaf** [comment]
>  It is a tricky balance to find and often "good enough" is highly subjective.

Running the full test suite does put a strain on the CIs and most of the time don't uncover packaging issues, but I am OK with them :smile: 

My rule of thumb is to avoid them when the package is too simple and/or the test will blow up the CIs time.

**Comment by pelson** [comment]
> It is a tricky balance to find and often "good enough" is highly subjective.

Indeed :smile: - if the full unit test can give us more confidence, and doesn't blow CI run time out of the water, then I'm completely :+1: on running them all. In some situations though, that isn't feasible.

That judgement is entirely down to the @conda-forge/pyamg team to find a balance that you are most comfortable with.

**Comment by jakevdp** [comment]
Tests take ~1 minute to run, so I think it's worth running them.
