### ISSUE TITLE
Cannot use pyamg as a dependency in windows build

### ISSUE THREAD

**Issue by renefritze** [conda-forge/pyamg-feedstock#18]
Issue: I get conda [build errors](https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/22024293?fullLog=true#L23925) with pyamg as a dependency in a [new recipe](https://github.com/conda-forge/staged-recipes/pull/7669) on conda-forge. 

The build environment is that of the conda-forge/staged-recipes repository on appveyor, which I have no real access to. Relevant info could be [here](https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/22024293?fullLog=true#L25) though

**Comment by xhochy** [comment]
@renefritze I requested a recipe rerender at https://github.com/conda-forge/pyamg-feedstock/pull/19 We should have a look at the build output to see whether this fixes the issue or whether this packages too much files.

**Comment by renefritze** [comment]
Alright, so I should trigger a rebuild of my recipe-PR once #19 is merged and see if that fixes my problem already?

**Comment by xhochy** [comment]
@renefritze Yes, you could try but I'm unsure whether this really makes a difference.

**Comment by jschueller** [comment]
pyamg windows packages contains all dependencies! 

check the archive: https://anaconda.org/conda-forge/pyamg/4.0.0/download/win-64/pyamg-4.0.0-py37h8300f20_1000.tar.bz2

no wonder why its huge

maybe the rerender will fix this

**Comment by jschueller** [comment]
@renefritze this seems to be fixed now, maybe you could close the issue ?

**Comment by renefritze** [comment]
OK
