### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by c-f-h** [conda-forge/pyamg-feedstock#5]
I don't know if this is being maintained and by whom, but if someone listens, Python 3.6 / numpy 1.12 support would be nice!

**Comment by ocefpaf** [comment]
You can find the maintainer in the recipe. See https://github.com/conda-forge/pyamg-feedstock/blob/master/recipe/meta.yaml#L39-L41

But if you are familiar with GitHub you can fix that yourself by sending a PR re-rendering this feedstock.
See http://conda-forge.github.io/docs/conda_smithy.html

**Comment by c-f-h** [comment]
Done. See #6. I hope that worked as expected.

**Comment by c-f-h** [comment]
Well, that one didn't work, not sure why. Anyway I tried to update to the latest pyamg 3.2.1, and after much gnashing of teeth, managed to fix the recipe to work with that version. It now also builds and runs all tests on all platforms.

The PR is #7. If anyone who actually knows what they're doing could review it, that would be great.

**Comment by jakevdp** [comment]
Now moved to #8
